apiVersion: v1
kind: Service
metadata:
  name: transaction
spec:
  selector:
    app: transaction
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8082 # HTTP
      nodePort: 30004
