apiVersion: v1
kind: Service
metadata:
  name: wallet
spec:
  selector:
    app: wallet
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8081 # HTTP
      nodePort: 30003
